version: '3'
networks:
  dbnet:
    external:
      name: dbnet

services:
  app1:
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 8081:8080
    networks:
      - dbnet    
    command: mvn clean spring-boot:run
  app2:
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 8082:8080
    networks:
      - dbnet
    command: mvn clean spring-boot:run
  app3:
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 8083:8080
    networks:
      - dbnet
    command: mvn clean spring-boot:run
  nginx:
    container_name: some-nginx
    image: nginx:1.13
    restart: always
    ports:
    - 80:80
    links:
     - app1:app1
     - app2:app2
     - app3:app3
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d