version: '3'
networks:
  dbnet:
    external:
      name: dbnet

services:
  app1:
    hostname: app1
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 8081:8081
    networks:
      - dbnet    
    command: mvn clean spring-boot:run -Drun.jvmArguments='-Dserver.port=8081'
  app2:
    hostname: app2
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 8082:8082
    networks:
      - dbnet
    command: mvn clean spring-boot:run -Drun.jvmArguments='-Dserver.port=8082'
  app3:
    hostname: app3
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 8083:8083
    networks:
      - dbnet
    command: mvn clean spring-boot:run -Drun.jvmArguments='-Dserver.port=8083'
  nginx:
    container_name: some-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
    depends_on: 
      - "app1"
      - "app2"
      - "app3"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d